[daq]
phys_channel = 1            # physical channel should be in range 1-4 (DIFF) or 1-8 (SE)
sample_rate = 1000.0        # in Hz
cutoff_frequency_hz = 10    # low-pass filter cutoff in hertz (Hz)
read_update_period = 0.1    # in seconds
input_mode = "DIFF"           # "SE" or "DIFF"
input_range = "BIP_10V"      # e.g. "BIP_1V", "BIP_5V", etc.

[display]
scope_time_base = 10.0      # in seconds
refresh_rate = 50           # in Hz
y_min = -10                 # in volts
y_max = 10                  # in volts

[writer]
write_rate = 50             # in Hz

[files]
output_data_file = "data.dat"
output_xlsx_file = "data.xlsx"

[conversion]
#load_scale = [-8.3693, -8.4055, 1.0, 1.0]   # [ch1, ch2, ch3, ch4]
#load_offset = [0.3460, 0.1067, 0.0, 0.0]      # [ch1, ch2, ch3, ch4]
load_scale = [-8.4786, -8.4428, 1.0, 1.0]   # [ch1, ch2, ch3, ch4]
load_offset = [0.2189, 0.0079, 0.0, 0.0]      # [ch1, ch2, ch3, ch4]

[gui]
initial_checked_channels = [1, 2]  # channels to check at startup (1-based)
initial_auto_zero_samples = 100     # number of samples to acquire before startup auto-zero
channel_names = ["Top", "Bottom", "", ""]  # display names for channels 1-4 (empty = no name)